/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 16600de1a157ca5a71afc5b3dd2bbdf8)
interface __BaseEnv_CloudflareEnv {
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	DB_HOST: string;
	DB_PORT: string;
	DB_USER: string;
	DB_PASSWORD: string;
	DB_NAME: string;
	DB_SSL: string;
	DB_SSL_CA_PATH: string;
	JWT_SECRET: string;
	ADMIN_SIGNUP_CODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DB_HOST" | "DB_PORT" | "DB_USER" | "DB_PASSWORD" | "DB_NAME" | "DB_SSL" | "DB_SSL_CA_PATH" | "JWT_SECRET" | "ADMIN_SIGNUP_CODE">> {}
}
