-- Auto-generated from data/categories.ts and data/products.ts
-- Run after schema.sql:  mysql -u <user> -p <database_name> < database/seed.sql

INSERT INTO categories (slug, name, description, image, accent) VALUES
  ('clothing', 'Baby Clothing', 'Soft cottons for everyday wear', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&q=80&auto=format&fit=crop', 'mint'),
  ('toys', 'Toys', 'Playtime that grows little minds', 'https://images.unsplash.com/photo-1558877385-1c4b7f5eba30?w=600&q=80&auto=format&fit=crop', 'sunshine'),
  ('feeding', 'Feeding', 'Mealtime made simple and safe', 'https://images.unsplash.com/photo-1621939514649-280e0a5019a9?w=600&q=80&auto=format&fit=crop', 'sky'),
  ('bath-care', 'Bath & Care', 'Gentle care from head to toe', 'https://images.unsplash.com/photo-1584582396905-c40a338f2b64?w=600&q=80&auto=format&fit=crop', 'peach'),
  ('accessories', 'Baby Accessories', 'Little extras for busy days', 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&q=80&auto=format&fit=crop', 'sage'),
  ('nursery', 'Nursery', 'Cozy corners for sweet dreams', 'https://images.unsplash.com/photo-1586683086743-9cdc0eabf5be?w=600&q=80&auto=format&fit=crop', 'mint'),
  ('gifts', 'Gifts', 'Thoughtful bundles for little ones', 'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=600&q=80&auto=format&fit=crop', 'sunshine');

INSERT INTO products (slug, name, category_slug, price, old_price, currency, rating, review_count, images, short_description, description, options, reviews, is_new, is_featured, stock, shipping_info) VALUES
  ('soft-cotton-baby-romper', 'Soft Cotton Baby Romper', 'clothing', 18.99, 24.99, '$', 4.8, 142, '["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1519457851969-91d0dc32a99c?w=900&q=80&auto=format&fit=crop"]', 'Breathable organic cotton romper for everyday cuddles.', 'Made from 100% organic cotton, this romper keeps little ones comfortable from nap time to playtime. A soft ribbed collar and easy snap closures make dressing a breeze, while the relaxed cut allows plenty of room to wiggle, crawl, and grow.', '[{"label":"Size","values":["0-3M","3-6M","6-12M"]},{"label":"Color","values":["Sage","Cream","Sky Blue"]}]', '[{"id":"r1","author":"Amara J.","rating":5,"comment":"So soft and the snaps make diaper changes so quick.","date":"2026-06-02"},{"id":"r2","author":"Priya S.","rating":4,"comment":"Lovely fabric, runs slightly big which is great for growing.","date":"2026-05-18"}]', 0, 1, 34, 'Ships in 1-2 business days. Free returns within 30 days.'),
  ('baby-elephant-plush-toy', 'Baby Elephant Plush Toy', 'toys', 15.5, NULL, '$', 4.9, 210, '["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1558877385-1c4b7f5eba30?w=900&q=80&auto=format&fit=crop"]', 'A huggable elephant friend for nap time and beyond.', 'Inspired by our very own TinyTods elephant, this plush toy is stitched from ultra-soft minky fabric and filled with hypoallergenic stuffing. Embroidered features mean no small parts, making it safe from day one.', '[{"label":"Size","values":["Small","Large"]}]', '[{"id":"r1","author":"Dilani F.","rating":5,"comment":"My daughter has not let go of this since it arrived.","date":"2026-07-11"}]', 1, 1, 58, 'Ships in 1-2 business days. Machine washable.'),
  ('silicone-feeding-set', 'Silicone Feeding Set', 'feeding', 22, 28, '$', 4.7, 96, '["https://images.unsplash.com/photo-1621939514649-280e0a5019a9?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1615486511262-c7ff5cae13be?w=900&q=80&auto=format&fit=crop"]', 'Suction bowl, plate and spoon set for early feeders.', 'Food-grade silicone that stays put with a strong suction base, so mealtime mess stays on the tray, not the floor. Dishwasher, microwave and freezer safe for easy meal prep.', '[{"label":"Color","values":["Mint","Peach","Sky"]}]', NULL, 0, 1, 40, 'Ships in 1-2 business days.'),
  ('cozy-baby-blanket', 'Cozy Baby Blanket', 'nursery', 26, NULL, '$', 4.9, 178, '["https://images.unsplash.com/photo-1586683086743-9cdc0eabf5be?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&q=80&auto=format&fit=crop"]', 'A featherlight knit blanket for swaddling and strolls.', 'Woven from a breathable cotton-bamboo blend, this blanket is light enough for summer naps and cozy enough for cool evenings. Finished with a scalloped edge inspired by TinyTods'' signature dashed trim.', NULL, NULL, 0, 1, 25, 'Ships in 1-2 business days.'),
  ('baby-bath-set', 'Baby Bath Set', 'bath-care', 19.99, 27.99, '$', 4.6, 87, '["https://images.unsplash.com/photo-1584582396905-c40a338f2b64?w=900&q=80&auto=format&fit=crop"]', 'Gentle wash, shampoo and hooded towel bundle.', 'A tear-free wash and shampoo paired with a plush hooded towel, formulated with calming chamomile for sensitive skin. Everything you need for a soothing bath-time routine.', NULL, NULL, 0, 1, 30, 'Ships in 1-2 business days.'),
  ('wooden-learning-blocks', 'Wooden Learning Blocks', 'toys', 21.5, NULL, '$', 4.8, 64, '["https://images.unsplash.com/photo-1558877385-1c4b7f5eba30?w=900&q=80&auto=format&fit=crop"]', 'Hand-painted blocks for stacking and sorting fun.', 'Sustainably sourced beechwood blocks finished with plant-based, non-toxic paint. Numbers, letters and shapes encourage early learning through open-ended play.', NULL, NULL, 1, 1, 45, 'Ships in 1-2 business days.'),
  ('baby-bib-set', 'Baby Bib Set', 'feeding', 12.99, NULL, '$', 4.5, 53, '["https://images.unsplash.com/photo-1615486511262-c7ff5cae13be?w=900&q=80&auto=format&fit=crop"]', 'A set of 3 wipeable bibs for tidier mealtimes.', 'Soft on the neckline, wipeable on the front — these bibs are built for real-life mealtimes. Adjustable snaps grow with your little one from first purees to finger foods.', NULL, NULL, 0, 1, 60, 'Ships in 1-2 business days.'),
  ('nursery-gift-box', 'Nursery Gift Box', 'gifts', 42, 55, '$', 5, 39, '["https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=900&q=80&auto=format&fit=crop"]', 'A curated welcome bundle for a new little one.', 'Wrapped in TinyTods signature packaging, this gift box brings together a plush toy, blanket, and keepsake card — a ready-to-give gift for baby showers and new arrivals.', NULL, NULL, 0, 1, 20, 'Ships in 1-2 business days. Gift wrap included.'),
  ('star-print-sleepsuit', 'Star Print Sleepsuit', 'clothing', 16.5, NULL, '$', 4.7, 71, '["https://images.unsplash.com/photo-1519457851969-91d0dc32a99c?w=900&q=80&auto=format&fit=crop"]', 'Footed sleepsuit with a dreamy star print.', 'Two-way zips make midnight changes simple, while the soft cotton jersey keeps little ones warm without overheating. Finished with the same starry motif as our logo.', '[{"label":"Size","values":["0-3M","3-6M","6-12M","12-18M"]}]', NULL, 0, 0, 38, 'Ships in 1-2 business days.'),
  ('stacking-rainbow-toy', 'Stacking Rainbow Toy', 'toys', 17, NULL, '$', 4.8, 58, '["https://images.unsplash.com/photo-1558877385-1c4b7f5eba30?w=900&q=80&auto=format&fit=crop"]', 'A wooden rainbow stacker for tiny hands.', 'Rounded, chunky pieces in soft pastel tones help build fine motor skills through stacking, sorting and imaginative play.', NULL, NULL, 0, 0, 42, 'Ships in 1-2 business days.'),
  ('gentle-baby-lotion', 'Gentle Baby Lotion', 'bath-care', 13.5, NULL, '$', 4.6, 49, '["https://images.unsplash.com/photo-1584582396905-c40a338f2b64?w=900&q=80&auto=format&fit=crop"]', 'Fragrance-light lotion for everyday softness.', 'A lightweight, fast-absorbing lotion made with shea butter and oat extract to keep delicate skin soft and comfortable all day.', NULL, NULL, 0, 0, 55, 'Ships in 1-2 business days.'),
  ('quilted-diaper-bag', 'Quilted Diaper Bag', 'accessories', 34, 44, '$', 4.7, 66, '["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&q=80&auto=format&fit=crop"]', 'A spacious, stylish bag for busy days out.', 'Quilted mint canvas with a wipeable lining, insulated bottle pockets, and a fold-out changing mat — everything for a day out, organized in one place.', NULL, NULL, 1, 0, 27, 'Ships in 1-2 business days.'),
  ('cloud-nursery-lamp', 'Cloud Nursery Lamp', 'nursery', 24.5, NULL, '$', 4.9, 44, '["https://images.unsplash.com/photo-1586683086743-9cdc0eabf5be?w=900&q=80&auto=format&fit=crop"]', 'A soft-glow lamp shaped like a little cloud.', 'Dimmable, warm LED light in a huggable cloud silhouette — a gentle glow for feedings, story time, and easing into sleep.', NULL, NULL, 0, 0, 33, 'Ships in 1-2 business days.'),
  ('first-birthday-gift-set', 'First Birthday Gift Set', 'gifts', 38, NULL, '$', 4.9, 22, '["https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=900&q=80&auto=format&fit=crop"]', 'A celebration bundle for a very big first year.', 'A keepsake bib, milestone cards, and a plush toy come together in this gift set — made for marking the little moments that lead to one big birthday.', NULL, NULL, 0, 0, 18, 'Ships in 1-2 business days. Gift wrap included.1');
